export const onShow = (payload) => ({ type: 'SHOW', payload })
export const showDisparo = (payload) => ({ type: 'SHOW_DISPARO', payload })
export const setShowSate = (payload) => ({ type: 'SHOW_STATE', payload })
export const logarShow = (payload) => ({ type: 'LOGAR_SHOW', payload })
export const acessoShow = (payload) => ({ type: 'ACESSO_SHOW', payload })